spring:
    datasource:
            username: postgres
            password: mysecretpassword
            url: jdbc:postgresql://localhost:25432/tmpl
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate.ddl-auto: update
        show-sql: true